name: Clone repository

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest
    
    steps:
      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ secrets.USERNAME }}@${{ secrets.HOST }} 
          privateKey: ${{ secrets.SSHKEY }}
          command: ls -lah
