name: Command via SSH

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: 'root@157.230.239.1'
          privateKey: ${{ secrets.SSHKEY }}
          command: ls -lah